apiVersion: v2
name: prefect-server
description: Prefect Server application bundle
type: application
version: "0.1.0"
appVersion: "0.1.0"
dependencies: 
- name: postgresql
  version: "~9.3.2"
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.useSubChart
